// AUTO-GENERATED by frontend/scripts/fetch-card-images.ts
// Do not edit by hand.

import type { ImageSourcePropType } from "react-native";

export const CARD_IMAGES: Record<string, ImageSourcePropType> = {
  "dog": require("./dog.jpg"),
  "cat": require("./cat.jpg"),
  "lion": require("./lion.webp"),
  "tiger": require("./tiger.jpg"),
  "elephant": require("./elephant.jpg"),
  "monkey": require("./monkey.webp"),
  "giraffe": require("./giraffe.jpg"),
  "zebra": require("./zebra.jpg"),
  "bear": require("./bear.jpg"),
  "bird": require("./bird.jpg"),
  "fish": require("./fish.jpg"),
  "horse": require("./horse.jpg"),
  "rabbit": require("./rabbit.webp"),
  "cow": require("./cow.jpg"),
  "sheep": require("./sheep.jpg"),
  "water": require("./water.jpg"),
  "food": require("./food.jpg"),
  "bathroom": require("./bathroom.jpg"),
  "airport": require("./airport.jpg"),
  "hotel": require("./hotel.jpg"),
  "train": require("./train.jpg"),
  "taxi": require("./taxi.jpg"),
  "police": require("./police.jpg"),
  "hospital": require("./hospital.jpg"),
  "morning": require("./morning.jpg"),
  "night": require("./night.jpg"),
  "money": require("./money.jpg"),
};
