import { StyleSheet } from "react-native";
import { AppColors } from "../../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: AppColors.background,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: AppColors.background,
  },
  header: {
    paddingTop: 16,
    paddingBottom: 10,
    alignItems: "center",
    gap: 10,
  },
  progressBarContainer: {
    width: "100%",
    height: 6,
    backgroundColor: AppColors.surfaceHighlight,
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: AppColors.primary,
    borderRadius: 3,
  },
  progressText: {
    color: AppColors.textMuted,
    fontSize: 14,
    fontWeight: "500",
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: "space-between",
  },
  card: {
    width: "100%",
    minHeight: 320,
    backgroundColor: AppColors.surface,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    backfaceVisibility: "hidden",
    shadowColor: AppColors.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: AppColors.border,
  },
  cardFront: {},
  cardBack: {
    position: "absolute",
    top: 0,
  },
  questionContentContainer: {
    alignItems: "center",
  },
  questionTitle: {
    color: AppColors.textSecondary,
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 20,
    textAlign: "center",
  },
  questionImage: {
    width: 220,
    height: 220,
    borderRadius: 20,
    marginBottom: 20,
  },
  questionWord: {
    fontSize: 42,
    fontWeight: "800",
    color: AppColors.text,
    marginBottom: 10,
  },
  optionsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 24,
    gap: 10,
  },
  optionButton: {
    backgroundColor: AppColors.surface,
    borderRadius: 14,
    padding: 18,
    marginBottom: 4,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: AppColors.borderLight,
    width: "48%",
  },
  imageOptionButton: {
    padding: 8,
  },
  correctOption: {
    backgroundColor: AppColors.correctBg,
    borderColor: AppColors.primary,
    borderWidth: 2,
  },
  wrongOption: {
    backgroundColor: AppColors.wrongBg,
    borderColor: AppColors.error,
    borderWidth: 2,
  },
  disabledOption: {
    opacity: 0.4,
  },
  optionImage: {
    width: 100,
    height: 100,
    borderRadius: 10,
  },
  optionText: {
    color: AppColors.text,
    fontSize: 17,
    fontWeight: "600",
    flex: 1,
    textAlign: "center",
  },
  input: {
    width: "100%",
    backgroundColor: AppColors.surface,
    color: AppColors.text,
    fontSize: 18,
    padding: 20,
    borderRadius: 14,
    textAlign: "center",
    marginTop: 24,
    borderWidth: 2,
    borderColor: AppColors.borderLight,
    fontWeight: "600",
  },
  footer: {
    paddingVertical: 10,
    minHeight: 80,
  },
  footerButton: {
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
    backgroundColor: AppColors.primary,
    shadowColor: AppColors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  footerButtonText: {
    color: AppColors.white,
    fontSize: 18,
    fontWeight: "700",
  },
  correctButton: {
    backgroundColor: AppColors.primary,
    shadowColor: AppColors.primary,
  },
  wrongButton: {
    backgroundColor: AppColors.error,
    shadowColor: AppColors.error,
  },
  feedbackCard: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  feedbackTitle: {
    color: AppColors.textMuted,
    fontSize: 16,
    marginBottom: 16,
  },
  feedbackImage: {
    width: 220,
    height: 220,
    borderRadius: 20,
    marginBottom: 20,
  },
  feedbackWord: {
    color: AppColors.text,
    fontSize: 34,
    fontWeight: "800",
  },
  feedbackTranslation: {
    color: AppColors.textSecondary,
    fontSize: 22,
    fontWeight: "500",
    marginTop: 4,
  },
});
